language: java
dist: bionic
jdk: openjdk11
env:
  global:
    - PYENV_VERSION=3.7.1
install:
  - pip3 install --user pre-commit
script:
  - pre-commit run --all-files --verbose
  - cd aws-accessanalyzer-analyzer
  # from Maven 3.6.1+, should use `--no-transfer-progress` instead of Slf4jMavenTransferListener
  - >
      mvn
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      -B
      clean verify
after_failure:
  - cat "$TRAVIS_BUILD_DIR/aws-accessanalyzer-analyzer/rpdk.log"
